import fs from 'node:fs';
import path from 'node:path';
import type { Article } from './db';

const TEMPLATE = (domain: string, sitesRoot: string) => `server {
    listen 80;
    listen [::]:80;
    server_name ${domain};

    root ${sitesRoot}/${domain};
    index index.html;
    charset utf-8;

    # security headers
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 256;

    location = /favicon.ico { access_log off; log_not_found off; }
    location ~* \\.(css|js|jpg|jpeg|png|gif|ico|svg|webp|woff2?)$ {
        expires 30d;
        access_log off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    # hide dotfiles
    location ~ /\\. { deny all; }
}
`;

export function generateNginxServerBlock(domain: string, sitesRoot: string): string {
  return TEMPLATE(domain, sitesRoot);
}

export function writeNginxConfig(articles: Article[], opts?: { sitesRoot?: string; outDir?: string; reload?: boolean }): { files: string[]; combinedPath: string } {
  const sitesRoot = opts?.sitesRoot || process.env.SITES_DIR || path.join(process.cwd(), 'public', 'sites');
  const outDir = opts?.outDir || process.env.NGINX_SITES_DIR || path.join(process.cwd(), 'nginx', 'sites');
  fs.mkdirSync(outDir, { recursive: true });

  const domains = new Set<string>();
  for (const a of articles) {
    if (a.status === 'published') domains.add(a.domain);
  }

  // one file per domain (easier to debug)
  for (const a of articles) {
    if (a.status !== 'published') continue;
    fs.writeFileSync(path.join(outDir, `${a.domain}.conf`), generateNginxServerBlock(a.domain, sitesRoot), 'utf8');
  }

  // combined include file with all server blocks
  const combined: string[] = ['# auto-generated by article-panel. do not edit by hand.\n'];
  for (const d of domains) combined.push(generateNginxServerBlock(d, sitesRoot));
  const combinedPath = path.join(outDir, '_all.conf');
  fs.writeFileSync(combinedPath, combined.join('\n'), 'utf8');

  return { files: Array.from(domains).map(d => path.join(outDir, `${d}.conf`)), combinedPath };
}

export function getNginxIncludeDirective(): string {
  return process.env.NGINX_INCLUDE_PATH || '/etc/nginx/sites-enabled/articles.conf';
}
